// 전국 골프장 목록 — tools/build_clubs.py로 생성. 직접 고치지 말고 tools/clubs_source.json을 고친 뒤 다시 생성.
// 코스 정보는 각 골프장 공식 홈페이지로 연결만 한다(내용 복제 없음).
// id: 메모·즐겨찾기 저장 키라서 바꾸면 안 된다. holes: 확인된 경우만, course: 공식 코스 안내 페이지(없으면 null)
export const AREAS = ["서울", "경기", "인천", "강원", "충북", "충남", "대전", "세종", "전북", "전남", "광주", "경북", "경남", "대구", "부산", "울산", "제주"];

export const CLUBS = [
  {"id": "가평베네스트GC", "name": "가평베네스트GC", "area": "경기", "region": "가평군", "holes": 27, "home": "https://www.benestgolf.com/", "course": "https://www.benestgolf.com/reve/pc/gp-course/main.do"},
  {"id": "크리스탈밸리CC", "name": "크리스탈밸리CC", "area": "경기", "region": "가평군", "holes": 18, "home": "https://www.crystalvalley.co.kr/", "course": "https://www.crystalvalley.co.kr/html/course/course01.asp"},
  {"id": "뉴코리아CC", "name": "뉴코리아CC", "area": "경기", "region": "고양시", "holes": 18, "home": "https://www.newkoreacc.co.kr/", "course": "https://www.newkoreacc.co.kr/course/course01.asp"},
  {"id": "서울한양CC", "name": "서울한양CC", "area": "경기", "region": "고양시", "holes": 36, "home": "https://www.hanyangcc.co.kr/", "course": "https://www.hanyangcc.co.kr/course/intro.asp"},
  {"id": "남촌GC", "name": "남촌GC", "area": "경기", "region": "광주시", "holes": 18, "home": "https://www.namchoncc.co.kr/", "course": "https://www.namchoncc.co.kr/Course/Course"},
  {"id": "뉴서울CC", "name": "뉴서울CC", "area": "경기", "region": "광주시", "holes": 36, "home": "https://www.newseoulgolf.co.kr/", "course": "https://www.newseoulgolf.co.kr/guide/course/courseInfo.asp"},
  {"id": "이스트밸리CC", "name": "이스트밸리CC", "area": "경기", "region": "광주시", "holes": 27, "home": "https://www.eastvalley.co.kr/", "course": "https://www.eastvalley.co.kr/pagesite/course/intro.asp"},
  {"id": "안양CC", "name": "안양CC", "area": "경기", "region": "군포시", "holes": 18, "home": "https://www.benestgolf.com/", "course": "https://www.benestgolf.com/reve/pc/ay-course/main.do"},
  {"id": "비전힐스CC", "name": "비전힐스CC", "area": "경기", "region": "남양주시", "holes": null, "home": "https://www.visionhillscc.co.kr/", "course": "https://www.visionhillscc.co.kr/course/course01.asp"},
  {"id": "남서울CC", "name": "남서울CC", "area": "경기", "region": "성남시", "holes": 18, "home": "https://www.nscc.co.kr/", "course": "https://www.nscc.co.kr/swp/course"},
  {"id": "더헤븐CC", "name": "더헤븐CC", "area": "경기", "region": "안산시", "holes": 27, "home": "https://www.theheavenresort.com/ISLANDRESORT/main.asp", "course": "https://www.theheavenresort.com/ISLANDRESORT/course_course.asp"},
  {"id": "마에스트로CC", "name": "마에스트로CC", "area": "경기", "region": "안성시", "holes": 18, "home": "https://www.maestrocc.co.kr/", "course": "https://www.maestrocc.co.kr/pagesite/course/intro.asp"},
  {"id": "레이크우드CC", "name": "레이크우드CC", "area": "경기", "region": "양주시", "holes": 36, "home": "https://lakewood.co.kr/", "course": "https://lakewood.co.kr/swp/course"},
  {"id": "송추CC", "name": "송추CC", "area": "경기", "region": "양주시", "holes": null, "home": "https://www.songchoo.co.kr/", "course": null},
  {"id": "블루헤런GC", "name": "블루헤런GC", "area": "경기", "region": "여주시", "holes": 18, "home": "https://www.blueheron.co.kr/", "course": "https://www.blueheron.co.kr/swp/course/outline"},
  {"id": "자유CC", "name": "자유CC", "area": "경기", "region": "여주시", "holes": null, "home": "https://www.jayucc.co.kr/", "course": null},
  {"id": "트리니티클럽", "name": "트리니티클럽", "area": "경기", "region": "여주시", "holes": null, "home": "https://www.trinityclub.co.kr/", "course": null},
  {"id": "페럼클럽", "name": "페럼클럽", "area": "경기", "region": "여주시", "holes": 18, "home": "https://www.ferrumclub.com/", "course": "https://www.ferrumclub.com/course/intro.asp"},
  {"id": "해슬리나인브릿지", "name": "해슬리나인브릿지", "area": "경기", "region": "여주시", "holes": null, "home": "https://www.haesley.com/", "course": null},
  {"id": "88CC", "name": "88CC", "area": "경기", "region": "용인시", "holes": 36, "home": "https://www.88countryclub.co.kr/", "course": "https://www.88countryclub.co.kr/Course/CourseInfo.aspx"},
  {"id": "남부CC", "name": "남부CC", "area": "경기", "region": "용인시", "holes": 18, "home": "https://www.namboocc.co.kr/", "course": "https://www.namboocc.co.kr/course/courseIntro.do"},
  {"id": "레이크사이드CC", "name": "레이크사이드CC", "area": "경기", "region": "용인시", "holes": 54, "home": "https://www.lakeside.kr/", "course": "https://www.lakeside.kr/course/courseIntro.do"},
  {"id": "수원CC", "name": "수원CC", "area": "경기", "region": "용인시", "holes": null, "home": "https://www.suwoncc.co.kr/", "course": null},
  {"id": "아시아나CC", "name": "아시아나CC", "area": "경기", "region": "용인시", "holes": 36, "home": "https://www.asianacc.co.kr/", "course": "https://www.asianacc.co.kr/course/index.asp"},
  {"id": "태광CC", "name": "태광CC", "area": "경기", "region": "용인시", "holes": 36, "home": "https://taekwangcc.co.kr/", "course": "https://taekwangcc.co.kr/introduction/course"},
  {"id": "플라자CC 용인", "name": "플라자CC 용인", "area": "경기", "region": "용인시", "holes": 36, "home": "https://www.plazacc.co.kr/plzcc/irsweb/golf2/main.do", "course": "https://www.plazacc.co.kr/plzcc/irsweb/golf2/course/yongin/yongin_club.do"},
  {"id": "화산CC", "name": "화산CC", "area": "경기", "region": "용인시", "holes": null, "home": "https://www.hwasancc.com/", "course": null},
  {"id": "비에이비스타CC", "name": "비에이비스타CC", "area": "경기", "region": "이천시", "holes": null, "home": "https://www.bavista.co.kr/", "course": null},
  {"id": "서원밸리CC", "name": "서원밸리CC", "area": "경기", "region": "파주시", "holes": 18, "home": "https://www.seowongolf.co.kr/valley/main", "course": "https://www.seowongolf.co.kr/valley/course/info"},
  {"id": "타이거CC", "name": "타이거CC", "area": "경기", "region": "파주시", "holes": 18, "home": "https://www.tigercc.co.kr/", "course": "https://www.tigercc.co.kr/course/course.asp"},
  {"id": "몽베르CC", "name": "몽베르CC", "area": "경기", "region": "포천시", "holes": null, "home": "https://www.montvertcc.com/", "course": "https://www.montvertcc.com/public/swp/courseInfo"},
  {"id": "아도니스CC", "name": "아도니스CC", "area": "경기", "region": "포천시", "holes": null, "home": "https://www.adoniscc.co.kr/", "course": null},
  {"id": "일동레이크GC", "name": "일동레이크GC", "area": "경기", "region": "포천시", "holes": null, "home": "https://www.ildonglakes.co.kr/", "course": null},
  {"id": "기흥CC", "name": "기흥CC", "area": "경기", "region": "화성시", "holes": null, "home": "https://www.ghcc.kr/", "course": null},
  {"id": "리베라CC", "name": "리베라CC", "area": "경기", "region": "화성시", "holes": 36, "home": "https://www.shinangolf.com/club/rivieracc", "course": "https://www.shinangolf.com/club/course/rivieracc"},
  {"id": "고창CC", "name": "고창CC", "area": "전북", "region": "고창군", "holes": 18, "home": "https://www.gochangcc.co.kr/", "course": "https://www.gochangcc.co.kr/html/course.asp"},
  {"id": "석정힐컨트리클럽", "name": "석정힐컨트리클럽", "area": "전북", "region": "고창군", "holes": 18, "home": "https://www.hillcc.com/", "course": "https://www.hillcc.com/swp/course_info"},
  {"id": "군산 골프&리조트", "name": "군산 골프&리조트", "area": "전북", "region": "군산시", "holes": 81, "home": "https://www.gunsancc.net/", "course": "https://www.gunsancc.net/main/golf"},
  {"id": "김제스파힐스컨트리클럽", "name": "김제스파힐스컨트리클럽", "area": "전북", "region": "김제시", "holes": 18, "home": "https://www.spahillscc.co.kr/", "course": "https://www.spahillscc.co.kr/course/intro"},
  {"id": "덕유산CC", "name": "덕유산CC", "area": "전북", "region": "무주군", "holes": 18, "home": "https://www.mdysresort.com/index.asp", "course": "https://www.mdysresort.com/golf/18hole_course.asp"},
  {"id": "웅포컨트리클럽", "name": "웅포컨트리클럽", "area": "전북", "region": "익산시", "holes": null, "home": "https://www.bearportcc.co.kr/index.asp", "course": "https://www.bearportcc.co.kr/pagesite/course/intro.asp"},
  {"id": "익산컨트리클럽", "name": "익산컨트리클럽", "area": "전북", "region": "익산시", "holes": null, "home": "https://santehill.co.kr/index.asp", "course": "https://santehill.co.kr/pagesite/course/intro.asp"},
  {"id": "전주샹그릴라컨트리클럽", "name": "전주샹그릴라컨트리클럽", "area": "전북", "region": "임실군", "holes": 27, "home": "https://www.jeonjucc.co.kr/", "course": "https://www.jeonjucc.co.kr/html/course/course01.asp"},
  {"id": "내장산CC", "name": "내장산CC", "area": "전북", "region": "정읍시", "holes": 18, "home": "https://www.naejangsancc.com/", "course": "https://www.naejangsancc.com/course/intro"},
  {"id": "광주컨트리클럽", "name": "광주컨트리클럽", "area": "전남", "region": "곡성군", "holes": 27, "home": "https://www.kjcc.co.kr/", "course": "https://www.kjcc.co.kr/html/course01.asp"},
  {"id": "골드레이크컨트리클럽", "name": "골드레이크컨트리클럽", "area": "전남", "region": "나주시", "holes": 36, "home": "https://www.goldlake.co.kr/", "course": "https://www.goldlake.co.kr/course/intro"},
  {"id": "해피니스컨트리클럽", "name": "해피니스컨트리클럽", "area": "전남", "region": "나주시", "holes": 45, "home": "https://www.happinesscc.com/", "course": "https://www.happinesscc.com/html/course01.asp"},
  {"id": "무안컨트리클럽", "name": "무안컨트리클럽", "area": "전남", "region": "무안군", "holes": 54, "home": "http://www.muangc.co.kr/", "course": "http://www.muangc.co.kr/course/course.php"},
  {"id": "순천컨트리클럽", "name": "순천컨트리클럽", "area": "전남", "region": "순천시", "holes": null, "home": "https://www.suncheoncc.co.kr/", "course": "https://www.suncheoncc.co.kr/course"},
  {"id": "파인힐스컨트리클럽", "name": "파인힐스컨트리클럽", "area": "전남", "region": "순천시", "holes": 27, "home": "https://www.pinehills.co.kr/pinehills/", "course": "https://www.pinehills.co.kr/pinehills/pagesite/course/intro.asp"},
  {"id": "디오션컨트리클럽", "name": "디오션컨트리클럽", "area": "전남", "region": "여수시", "holes": 18, "home": "https://www.theoceanresort.co.kr/", "course": "https://www.theoceanresort.co.kr/country/GolfCourse"},
  {"id": "웨스트오션컨트리클럽", "name": "웨스트오션컨트리클럽", "area": "전남", "region": "영광군", "holes": 18, "home": "https://www.westoceancc.co.kr/", "course": "https://www.westoceancc.co.kr/html/course/course01.asp"},
  {"id": "아크로컨트리클럽", "name": "아크로컨트리클럽", "area": "전남", "region": "영암군", "holes": 27, "home": "https://www.acrogolf.co.kr/", "course": "https://www.acrogolf.co.kr/html/course/course_01.asp"},
  {"id": "정남진골프리조트", "name": "정남진골프리조트", "area": "전남", "region": "장흥군", "holes": 27, "home": "https://www.jnjgolfresort.co.kr/", "course": "https://www.jnjgolfresort.co.kr/swp/course"},
  {"id": "함평엘리체컨트리클럽", "name": "함평엘리체컨트리클럽", "area": "전남", "region": "함평군", "holes": 27, "home": "https://www.hpelichecc.co.kr/hampyeong/index.asp", "course": "https://www.hpelichecc.co.kr/hampyeong/html/course/course01.asp"},
  {"id": "솔라시도컨트리클럽", "name": "솔라시도컨트리클럽", "area": "전남", "region": "해남군", "holes": 18, "home": "https://www.solaseadocc.com/", "course": "https://www.solaseadocc.com/sub/course.asp"},
  {"id": "파인비치골프링크스", "name": "파인비치골프링크스", "area": "전남", "region": "해남군", "holes": 27, "home": "https://www.pinebeachcc.co.kr/", "course": "https://www.pinebeachcc.co.kr/course/intro.asp"},
  {"id": "화순컨트리클럽", "name": "화순컨트리클럽", "area": "전남", "region": "화순군", "holes": 27, "home": "https://www.hwasuncc.co.kr/", "course": "https://www.hwasuncc.co.kr/course/courseIntro.asp"},
  {"id": "어등산컨트리클럽", "name": "어등산컨트리클럽", "area": "광주", "region": "광산구", "holes": 27, "home": "https://www.eodeungsancc.com/", "course": "https://www.eodeungsancc.com/course-introduction/ed-course"},
  {"id": "빛고을CC", "name": "빛고을CC", "area": "광주", "region": "남구", "holes": 9, "home": "https://www.bitgoeulcc.co.kr/web/index.do", "course": "https://www.bitgoeulcc.co.kr/web/course/outline.do"},
];
